### ISSUE TITLE
JSON problems

### ISSUE THREAD

**Issue by jesperldk** [ibaca/autorest-nominatim-example#1]
Hi, sorry if this (again) is a question only exposing my own ignorance ;-) I would appreciate a short answer, perhaps a pointer to some tutorial or reference documentation.

I have made some changes in my own copy of the nominatim example to try to get the hang of things.
I have made a new subclass of SearchResult, using @JsonTypeInfo on the root class. 
I have also made a new @POST method that takes a SearchResult as argument and returns an Observable<SearchResult>, it will return a mix of instances of the root SearchResult and of the new subclass.

On the server side this seems to work. When I inspect the JSON it returns, it has the correct type field identifying the class.

On the client this seems to be ignored - I always get a root SearchResult and never an instance of the subclass.

When I call the new post method with an SearchResult as argument, the request get serialized without the type-argument, and Jackson correctly complains on the server side that it is missing.

To me it looks like the @JsonTypeInfo is used correctly on the server side, but is ignored on the client side.

My problem also is, that while I have a little idea of how Jersey and Jackson works with the ApplicationJacksonModule on the server, am I clueless on how the JSON (de)serialization works on the client, and I have not been able to find a good (or any) introduction to that.

**Comment by jesperldk** [comment]
OK, stupid me - of course is my @JsonTypeInfo no longer available in the JavaScript code. But I am still clueless about what to do then...
I can see that RestyGWT supports @JsonTypeInfo - but how do I make something similar with autorest?

**Comment by ibaca** [comment]
Yep, not easy at all. Actually, this is more a JsInterop question than a autorest one. I personally will try to avoid this situation, you can maybe use inheritance, but try to return a specific type on each endpoint. This is not a crazy idea, in java looks like everything should be designed using inheritance, but... if you look at many API, using inheritance is not as common as you may think (https://apis.guru/openapi-directory/).

If it really improve your code, I have thought a pretty easy strategy. Expose the typeInfo parameter in the root model, and create an overlay to cast to the subtype, maybe using a per-type callback. Something like...
```java
class Root {
  String type;
  @JsOverlay void cast(RootCast fn) {
    switch(type) {
      case "A": fn.a((A) this);
      case "B": fn.b((B) this);
    }
  }
}
class A extends Root {}
class B extends Root {}
```

**Comment by jesperldk** [comment]
OK, I get it now. I also think I get why JsInterop has this limitation, but at the same time think that Google needs to come up with something for this kinds of problems. Sorry to hijack this issue with this, but I would think it is relevant for many who wants to use AutoRest.
I don't in general disagree with your thoughts of not using inheritance in an API. However, sometimes it really is the only solutions unless you want an explosion of endpoints in your API, and sometimes it is the only natural API.

I have come up with the following:

I declare my root like this
```
@JsonTypeInfo(use=JsonTypeInfo.Id.MINIMAL_CLASS, include=JsonTypeInfo.As.PROPERTY, property="$type")
@JsType(isNative = true, namespace = JsPackage.GLOBAL, name = "Object") 
public class Root implements Root_Helper {
	@JsonIgnore public transient String $type;
```
and subclasses like this
```
@JsType(isNative = true, namespace = JsPackage.GLOBAL, name = "Object")
public class Sub extends Root {
	public String s;
```

This makes Jackson do its magic in fully standard way on the server. On the server I can code with inheritance without thinking about it.

On the client you have to think a little, because instanceof does not work. As a solution I have a Java processor that generates the Root_Helper interface. In this I could generate your cast method, but I am not sure I like that pattern. For now I generate methods, so I can write things like
```
ressource.get().filter(Root::instanceOfSub).map(Root::asSub).forEach(sub -> log(sub.s));
```
and like
```
Sub sub = Root_Helper.createSub();
```

This makes me confident to move ahead. No magic, just a processor that generates a little boilerplate code I could write my self if I had to ;-)

**Comment by ibaca** [comment]
Yep, this sounds like autorest itself. Try to find a solution as simple as possible based on modern GWT (native XMLHttpRequest and JsInterop), and at the same time try to make it match with the server (Jackson). This has a lot of limitations, but at the end, applying all this limitations end up making your code/api even more simple and clear.
